### ISSUE TITLE
报错OSError: [Errno 22] Invalid argument

### ISSUE THREAD

**Issue by LLLiaomeng** [LeeSureman/Flat-Lattice-Transformer#12]
请问一下，您知道这个错误咋解决吗，resume和weibo两个数据集都会报这个错误。

>Traceback (most recent call last):
  File "flat_main.py", line 313, in <module>
    only_train_min_freq=args.only_train_min_freq)
  File "D:\develop\python\Anaconda3\lib\site-packages\fastNLP\core\utils.py", line 160, in wrapper
    with open(cache_filepath, 'wb') as f:
OSError: [Errno 22] Invalid argument: 'cache\\weibo_lattice_only_train:False_trainClip:True_norm_num:0char_min_freq1bigram_min_freq1word_min_freq1only_train_min_freqTruenumber_norm0lexicon_yjload_dataset_seed100'

*相关代码*
```python
datasets,vocabs,embeddings = equip_chinese_ner_with_lexicon(datasets,vocabs,embeddings,
                                                            w_list,yangjie_rich_pretrain_word_path,
                                                         _refresh=refresh_data,_cache_fp=cache_name,
                                                         only_lexicon_in_train=args.only_lexicon_in_train,
                                                            word_char_mix_embedding_path=yangjie_rich_pretrain_char_and_word_path,
                                                            number_normalized=args.number_normalized,
                                                            lattice_min_freq=args.lattice_min_freq,
                                                            only_train_min_freq=args.only_train_min_freq)
```
应该是这个注解产生的错误吧。
```python
@cache_results(_cache_fp='need_to_defined_fp',_refresh=True)
def equip_chinese_ner_with_lexicon(datasets,vocabs,embeddings,w_list,word_embedding_path=None,
                                   only_lexicon_in_train=False,word_char_mix_embedding_path=None,
                                   number_normalized=False,
                                   lattice_min_freq=1,only_train_min_freq=0):
```

**Comment by LeeSureman** [comment]
嗯有可能，因为这是一个路径，可能linux系统和windows系统对路径名的规范有点不一样

**Comment by ZR5932** [comment]
请问这个问题最后解决了么？是哪里有问题么？要怎么改呢？

**Comment by hongdangshao** [comment]
>我也遇到了这个问题，具体怎么改呢？上述代码中路径没有冒号啊！
