### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 

### ISSUE THREAD

**Issue by C929-x** [LeeSureman/Flat-Lattice-Transformer#126]
Traceback (most recent call last):
  File "E:\yan\chong\daimaDemo\Flat-Lattice-Transformer-master\Flat-Lattice-Transformer-master\V0\flat_main.py", line 290, in <module>
    datasets, vocabs, embeddings = equip_chinese_ner_with_lexicon(datasets, vocabs, embeddings,
  File "D:\Anaconda3\lib\site-packages\fastNLP\core\utils.py", line 160, in wrapper
    with open(cache_filepath, 'wb') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'cache\\weibo_lattice_only_train#False_trainClip#True_norm_num#0char_min_freq1bigram_min_freq1word_min_freq1only_train_min_freqTruenumber_norm0lexicon_yjload_dataset_seed100'

在Windows上跑遇到了这个遇到了这个问题，请问是什么问题怎么解决呢

**Comment by EthanLeeGeek** [comment]
同问

**Comment by C929-x** [comment]
> 

你是Windows系统吗

**Comment by C929-x** [comment]
#

**Comment by YMXBL** [comment]
可能是cache_name路径里有“:”或者其他符号，我删掉就可以运行了

**Comment by EthanLeeGeek** [comment]
是的，将flat_main.py文件中的cache_name = os.path.join('cache',(args.dataset+'_lattice'+'_only_train:{}'+ '_trainClip:{}'+'_norm_num:{}' 改为 cache_name = os.path.join('cache',(args.dataset+'_lattice'+'_only_train#{}'+'_trainClip#{}'+'_norm_num#{}'就可以了。

**Comment by C929-x** [comment]
你好请问·你是Windows系统吗，之前我就是照着这样改的，结果还报错，不知道为啥


四年
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "LeeSureman/Flat-Lattice-Transformer"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年7月21日(星期五) 下午4:36
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [LeeSureman/Flat-Lattice-Transformer] FileNotFoundError: [Errno 2] No such file or directory:  (Issue #126)





 
是的，将flat_main.py文件中的cache_name = os.path.join('cache',(args.dataset+'_lattice'+'_only_train:{}'+ '_trainClip:{}'+'_norm_num:{}' 改为 cache_name = os.path.join('cache',(args.dataset+'_lattice'+'_only_train#{}'+'_trainClip#{}'+'_norm_num#{}'就可以了。
