### ISSUE TITLE
weibo数据集找不到_deseg后缀的文件

### ISSUE THREAD

**Issue by isolet** [LeeSureman/Flat-Lattice-Transformer#17]
原始数据集里只有.train/.dev/.test的文件？

```
Traceback (most recent call last):
  File "flat_main.py", line 254, in <module>
    only_train_min_freq=args.only_train_min_freq,
  File "/Users/user/.pyenv/versions/env-mkwPXnF--py3.7/lib/python3.7/site-packages/fastNLP/core/utils.py", line 344, in wrapper
    results = func(*args, **kwargs)
  File "../load_data.py", line 646, in load_weibo_ner
    bundle = loader.load(v)
  File "/Users/user/.pyenv/versions/env-mkwPXnF--py3.7/lib/python3.7/site-packages/fastNLP/io/loader/loader.py", line 68, in load
    paths = check_loader_paths(paths)
  File "/Users/user/.pyenv/versions/env-mkwPXnF--py3.7/lib/python3.7/site-packages/fastNLP/io/utils.py", line 63, in check_loader_paths
    raise FileNotFoundError(f"{paths} is not a valid file path.")
FileNotFoundError: /Users/user/Downloads/Flat-Lattice-Transformer/V0/WeiboNER/weiboNER_2nd_conll.train_deseg is not a valid file path.
```

**Comment by LeeSureman** [comment]
不好意思，我忘记这个细节了。原本的weibo数据集中是有个分词信息的，我为了使得它的格式就预处理了一份和conll格式一样的，没分词信息的文件（就是把分词标号那一列删掉），可以加我微信18158037912，我把那个预处理后的文件给你

**Comment by EricLee8** [comment]
同求一份

**Comment by Eason-zz** [comment]
原始数据集是哪一个文件

**Comment by LawsonAbs** [comment]
> 
> 
> 原始数据集是哪一个文件

原始数据集是叫 WeiboNER ，可以在链接https://github.com/hltcoe/golden-horse/tree/master/data 中下载（）

**Comment by LeeSureman** [comment]
> > 原始数据集是哪一个文件
> 
> 原始数据集是叫 WeiboNER ，可以在链接https://github.com/hltcoe/golden-horse/tree/master/data 中下载（）

感谢老哥帮忙回复

**Comment by LawsonAbs** [comment]
> 
> 
> 不好意思，我忘记这个细节了。原本的weibo数据集中是有个分词信息的，我为了使得它的格式就预处理了一份和conll格式一样的，没分词信息的文件（就是把分词标号那一列删掉），可以加我微信18158037912，我把那个预处理后的文件给你

可以告诉我们，做了哪些处理方法吗？现在我重新使用另外一个数据集，不知道该怎么处理原文本信息，还希望作者指教一下！

**Comment by LawsonAbs** [comment]
> 
> 
> > > 原始数据集是哪一个文件
> > 
> > 
> > 原始数据集是叫 WeiboNER ，可以在链接https://github.com/hltcoe/golden-horse/tree/master/data 中下载（）
> 
> 感谢老哥帮忙回复

开源世界，这是我该做哒~

**Comment by Eason-zz** [comment]
> > 原始数据集是哪一个文件
> 
> 原始数据集是叫 WeiboNER ，可以在链接https://github.com/hltcoe/golden-horse/tree/master/data 中下载（）

感谢

**Comment by Ritian-Li** [comment]
> > > > 原始数据集是哪一个文件
> > > 
> > > 
> > > 原始数据集是叫 WeiboNER ，可以在链接https://github.com/hltcoe/golden-horse/tree/master/data 中下载（）
> > 
> > 
> > 感谢老哥帮忙回复
> 
> 开源世界，这是我该做哒~

大哥，处理后的文件是这个样子的吗
![image](https://user-images.githubusercontent.com/60093100/96400292-eec42a80-1202-11eb-8578-e66aabbdaa91.png)

**Comment by WoJiaoWangZhenRen** [comment]
同求预处理后的文件

**Comment by sssssajfsd** [comment]
求一份预处理文件。可以帮忙发一份吗？

**Comment by WoJiaoWangZhenRen** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "LeeSureman/Flat-Lattice-Transformer"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月25日(星期天) 晚上7:47
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [LeeSureman/Flat-Lattice-Transformer] weibo数据集找不到_deseg后缀的文件 (#17)





 
求一份预处理文件。可以帮忙发一份吗？

**Comment by shenhuaze** [comment]
我按照作者的说明，去除了weiboNER_2nd_conll数据集的分词信息，需要的可以直接下载：https://github.com/shenhuaze/weibo-ner-conll
