### ISSUE TITLE
一个简单的bug

### ISSUE THREAD

**Issue by YuMo10** [LeeSureman/Flat-Lattice-Transformer#45]
Traceback (most recent call last):
  File "E:/yuan/Flat-Lattice-Transformer-master/V0/flat_main.py", line 306, in <module>
    only_train_min_freq=args.only_train_min_freq)
  File "C:\ProgramData\Anaconda3\envs\flat\lib\site-packages\fastNLP\core\utils.py", line 160, in wrapper
    with open(cache_filepath, 'wb') as f:
OSError: [Errno 22] Invalid argument: 'cache\\resume_lattice_only_train:False_trainClip:True_norm_num:0char_min_freq1bigram_min_freq1word_min_freq1only_train_min_freqTruenumber_norm0lexicon_yjload_dataset_seed100'
这个怎么解决啊

**Comment by LeeSureman** [comment]
在运行目录下建一个cache文件夹试试，另外可能此代码不完全支持windows，我只在linux环境下跑过

**Comment by wn1652400018** [comment]
我也报了这个错误，不知道怎么解决。

**Comment by Ludong418** [comment]
> 我也报了这个错误，不知道怎么

> Traceback (most recent call last):
> File "E:/yuan/Flat-Lattice-Transformer-master/V0/flat_main.py", line 306, in
> only_train_min_freq=args.only_train_min_freq)
> File "C:\ProgramData\Anaconda3\envs\flat\lib\site-packages\fastNLP\core\utils.py", line 160, in wrapper
> with open(cache_filepath, 'wb') as f:
> OSError: [Errno 22] Invalid argument: 'cache\resume_lattice_only_train:False_trainClip:True_norm_num:0char_min_freq1bigram_min_freq1word_min_freq1only_train_min_freqTruenumber_norm0lexicon_yjload_dataset_seed100'
> 这个怎么解决啊

window系统文件名称命名错误，文件不允许有 ':' 符号， 把 'cache\resume_lattice_only_train:False_trainClip:True_norm_num:0char_min_freq1bigram_min_freq1word_min_freq1only_train_min_freqTruenumber_norm0lexicon_yjload_dataset_seed100' 中的 ':' 符号，修改成 '-' 号即可。

**Comment by wn1652400018** [comment]
感谢






------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Ludong418"<notifications@github.com&gt;; 
发送时间: 2020年12月3日(星期四) 凌晨1:53
收件人: "LeeSureman/Flat-Lattice-Transformer"<Flat-Lattice-Transformer@noreply.github.com&gt;; 
抄送: "微冷/不觉寒"<1652400018@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [LeeSureman/Flat-Lattice-Transformer] 一个简单的bug (#45)





  
我也报了这个错误，不知道怎么
   
Traceback (most recent call last):
 File "E:/yuan/Flat-Lattice-Transformer-master/V0/flat_main.py", line 306, in
 only_train_min_freq=args.only_train_min_freq)
 File "C:\ProgramData\Anaconda3\envs\flat\lib\site-packages\fastNLP\core\utils.py", line 160, in wrapper
 with open(cache_filepath, 'wb') as f:
 OSError: [Errno 22] Invalid argument: 'cache\resume_lattice_only_train:False_trainClip:True_norm_num:0char_min_freq1bigram_min_freq1word_min_freq1only_train_min_freqTruenumber_norm0lexicon_yjload_dataset_seed100'
 这个怎么解决啊
  
window系统文件名称命名错误，文件不允许有 ':' 符号， 把 'cache\resume_lattice_only_train:False_trainClip:True_norm_num:0char_min_freq1bigram_min_freq1word_min_freq1only_train_min_freqTruenumber_norm0lexicon_yjload_dataset_seed100' 中的 ':' 符号，修改成 '-' 号即可。
