### ISSUE TITLE
use   python flat_main.py --device "cpu" 出现 ValueError: There is no usable gpu. set `device` as `cpu` or `None`.

### ISSUE THREAD

**Issue by s1162276945** [LeeSureman/Flat-Lattice-Transformer#69]
Traceback (most recent call last):
  File "flat_main.py", line 582, in <module>
    check_code_level=-1)
  File "D:\Anaconda3\lib\site-packages\fastNLP\core\trainer.py", line 499, in __init__
    self.model = _move_model_to_device(model, device=device)
  File "D:\Anaconda3\lib\site-packages\fastNLP\core\utils.py", line 228, in _move_model_to_device
    raise ValueError("There is no usable gpu. set `device` as `cpu` or `None`.")
ValueError: There is no usable gpu. set `device` as `cpu` or `None`.

**Comment by LeeSureman** [comment]
可能你的运行环境没有显卡？

**Comment by s1162276945** [comment]
> 可能你的运行环境没有显卡？

是的，所以我用cpu跑着测试一下

**Comment by zelin-x** [comment]
也可能是pytorch与cuda版本不对应,也会报这个错误

**Comment by houyuchao** [comment]
> > 可能你的运行环境没有显卡？
> 
> 是的，所以我用cpu跑着测试一下

用cpu跑只需要将device设置成cpu就可以把，但是我爆出了这个错误
![image](https://github.com/LeeSureman/Flat-Lattice-Transformer/assets/162104094/fdfd7421-acf9-4305-acdf-1f6a3d8bf5ac)
