### ISSUE TITLE
运行flat_main.py的时候报错

### ISSUE THREAD

**Issue by xiaoyao0104** [LeeSureman/Flat-Lattice-Transformer#9]
Traceback (most recent call last):
  File "flat_main.py", line 615, in <module>
    check_code_level=-1)
  File "/home/iiotxiaoyao/anaconda3/lib/python3.7/site-packages/fastNLP/core/trainer.py", line 499, in __init__
    self.model = _move_model_to_device(model, device=device)
  File "/home/iiotxiaoyao/anaconda3/lib/python3.7/site-packages/fastNLP/core/utils.py", line 228, in _move_model_to_device
    raise ValueError("There is no usable gpu. set `device` as `cpu` or `None`.")
ValueError: There is no usable gpu. set `device` as `cpu` or `None`.

**Comment by xiaoyao0104** [comment]
none
